### ISSUE TITLE
Incorrect number of days displayed when viewing website

### ISSUE THREAD

**Issue by NHGmaniac** [Ashtonian/dayssincenpmbroke.com#1]
The Website shows the incorrect number of days.
Days displayed: 00 (See attached screenshot)
![bildschirmfoto_2018-02-23_02-25-19](https://user-images.githubusercontent.com/23729480/36573372-e24ddae4-1840-11e8-8d16-7f971b34645b.png)
Actual number of days since npm broke: 2963

Tested with Firefox 58.0.2

**Comment by vincentlarkin** [comment]
Are you a nodejs developer, by any chance?

**Comment by ashtonian** [comment]
behaving as intended

**Comment by NHGmaniac** [comment]
@VinLark i sure as hell wont touch the burning dumpsterfire that as is nodejs and javascript in general, so no.
@Ashtonian you sure? npm was released about 2964 days ago, and i dont remember it ever being not broken, so i think its broken since then.
